# Generated by Django 5.0.6 on 2026-06-17 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentfolder',
            options={'ordering': ['name']},
        ),
    ]
